[profile.default]
src = "src"
out = "out"
libs = [
    "../../node_modules"
]
allow_paths = [
    "../../node_modules"
]
fs_permissions = [{ access = "read", path = "./" }, { access = "read", path = "../../node_modules" }]