name: release-liquidity

on:
  push:
    tags:
      - 'release-liquidity-*'
    branches:
      - 'liquidity-synthetix-eth'
      - 'releases'

jobs:
  release-liquidity:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global user.email engineering@snxdao.io
      - run: git config --global user.name synthetix-team

      - uses: actions/checkout@v4
        with:
          path: liquidity-ui
          ref: '${{ github.sha }}'

      - run: yarn workspaces focus @snx-v3/liquidity
        working-directory: liquidity-ui

      - run: yarn workspace @snx-v3/liquidity build
        working-directory: liquidity-ui

      - uses: actions/checkout@v4
        with:
          path: liquidity.synthetix.eth
          repository: 'Synthetixio/liquidity.synthetix.eth'
          ref: 'master'
          ssh-key: '${{ secrets.LIQUIDITY_SSH_KEY }}'

      - run: rm -rf ./liquidity.synthetix.eth/*

      - run: git checkout HEAD -- CNAME || true
        working-directory: liquidity.synthetix.eth

      - run: cp -r ./liquidity-ui/liquidity/ui/dist/* ./liquidity.synthetix.eth/

      - run: git add .
        working-directory: liquidity.synthetix.eth

      - run: |
          git commit -m "Release ${{ github.event.release.name }}" \
            --allow-empty \
            -m "Source: ${{ github.server_url}}/${{ github.repository }}" \
            -m "Commit: ${{ github.sha }}"
        working-directory: liquidity.synthetix.eth

      - run: git push origin master
        working-directory: liquidity.synthetix.eth

      - uses: actions/checkout@v4
        with:
          path: liquidity.synthetix.io
          repository: 'Synthetixio/liquidity.synthetix.io'
          ref: 'master'
          ssh-key: '${{ secrets.LIQUIDITY_SYNTHETIX_IO_SSH_KEY }}'

      - run: rm -rf ./liquidity.synthetix.io/*

      - run: git checkout HEAD -- CNAME || true
        working-directory: liquidity.synthetix.io

      - run: cp -r ./liquidity-ui/liquidity/ui/dist/* ./liquidity.synthetix.io/

      - run: git add .
        working-directory: liquidity.synthetix.io

      - run: |
          git commit -m "Release ${{ github.event.release.name }}" \
            --allow-empty \
            -m "Source: ${{ github.server_url}}/${{ github.repository }}" \
            -m "Commit: ${{ github.sha }}"
        working-directory: liquidity.synthetix.io

      - run: git push origin master
        working-directory: liquidity.synthetix.io
